[tool.poetry]
name = "nlp"
version = "0.1.0"
description = ""
authors = ["finn <finn@cofenster.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
watchdog = "^3.0.0"
stanza = "^1.7.0"
fastapi = "^0.108.0"
uvicorn = "^0.25.0"
pydantic = "^2.5.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
