"""A curriculum is a collection of Units and Games."""
type Curriculum {
  gameRelations: [CurriculumGameRelation!]!
  id: ID!
  name: String!
}

"""The relation between a curriculum and a game"""
type CurriculumGameRelation {
  curriculum: Curriculum!
  game: Game!
  id: ID!
}

"""
A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
"""
scalar DateTime

"""A Game"""
type Game {
  curriculumRelation: CurriculumGameRelation!
  id: ID!
  type: GameTypeEnum!
  typePretty: String!
}

enum GameTypeEnum {
  FLASHCARDS
  TRANSLATIONS
}

type Game_Flashcards_Card {
  back: String!
  front: String!
  unitId: ID!
}

input Game_Flashcards_GetCards_Input {
  blacklist: [String!]
  fetch: Int!
  gameId: ID!
}

enum Game_Flashcards_ReviewResponses_Enum {
  GRADUATE
  KNOWN
  UNKNOWN
}

input Game_Flashcards_UpdateCard_Input {
  gameId: ID!
  response: Game_Flashcards_ReviewResponses_Enum!
  unitId: ID!
}

type Game_Flashcards_UpdateCard_Response {
  unitId: ID!
}

type Game_Translations_Evaluate_Response {
  gameId: ID!
}

enum Game_Translations_Feedback_Classification_Enum {
  correct
  failure
  info
  mistake
}

type Game_Translations_Feedback_Part {
  classification: Game_Translations_Feedback_Classification_Enum!
  correction: String
  part: String!
  translation: String!
}

type Game_Translations_Feedback_Response {
  classification: Game_Translations_Feedback_Classification_Enum!
  correction: String
  gameId: ID!
  parts: [Game_Translations_Feedback_Part!]!
  score: Float!
  summary: String!
}

input Game_Translations_GetSentence_Input {
  gameId: ID!
}

type Game_Translations_Sentence {
  learning: String!
  payload: String!
  spoken: String!
}

input Game_Translations_SentenceTranslation_Input {
  gameId: ID!
  learning: String!
  payload: String!
  spoken: String!
  translation: String!
}

"""
The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSON

type Mutation {
  Game_Flashcards_UpdateCard(input: Game_Flashcards_UpdateCard_Input!): Game_Flashcards_UpdateCard_Response!
  Game_Translations_Evaluate(input: Game_Translations_SentenceTranslation_Input!): Game_Translations_Evaluate_Response!
  Game_Translations_Feedback(input: Game_Translations_SentenceTranslation_Input!): Game_Translations_Feedback_Response!
}

type Query {
  Game_Flashcards_GetCards(input: Game_Flashcards_GetCards_Input!): [Game_Flashcards_Card!]!
  Game_Translations_GetSentence(input: Game_Translations_GetSentence_Input!): Game_Translations_Sentence!
  curriculumsRead: [Curriculum!]!
  gameRead(id: ID!): Game!
}
