"""A curriculum is a collection of Units and Games."""
type Curriculum {
  gameRelations: [CurriculumGameRelation!]!
  id: ID!
  name: String!
}

"""The relation between a curriculum and a game"""
type CurriculumGameRelation {
  curriculum: Curriculum!
  game: Game!
  id: ID!
}

"""
A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
"""
scalar DateTime

"""One Card"""
type FlashcardsGameCard {
  back: String!
  front: String!
  unitId: ID!
}

"""The initial game setup for flashcards"""
type FlashcardsSetupObject {
  cards: [FlashcardsGameCard!]!
  curriculumId: ID!
  gameId: ID!
}

"""A Game"""
type Game {
  curriculumRelation: CurriculumGameRelation!
  id: ID!
  type: GameTypeEnum!
  typePretty: String!
}

enum GameTypeEnum {
  FLASHCARDS
}

"""
The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSON

type Query {
  curriculumsRead: [Curriculum!]!

  """Initialize the flashcards game. Returns the first review items."""
  flashcardsInit(blacklist: [String!], fetch: Int!, gameId: ID!): FlashcardsSetupObject!
  gameRead(id: ID!): Game!
}
