version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./services/database-postgres/.env.postgres
    # networks:
    #   - localhost
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

# networks:
#   localhost:
#     name: localhost
