*  
differentiate estate from institution(virtual koerperschaft, legal entity) and private.
estate being any state function, digital state service, state service provisioning, facilitation or execution. license is some fraction of current(koerperschaft).

high level i split into institutial and private use.
where private use is for self or in private social context.
and where institutional is any b2b b2g ngo isp or other usage.
where the core separating idea is that the koerperschaft provides vivalence to others.

for self and for other.
private and institutional.
personhood and koerperschaft.

and hosting for others is considered a different variant.
where private for other is subject to the same licence-granted freedoms as private for self.
/ we might offer to facilitate some metadata aggregation to allow for trusted entities.

institutional use: (for self is not allowed under personhood)  
usage rights can be obtained.
programatically. 
flat fee. f(Set(persons, for other))
i determin price f, everyone pays the same.
price is pegged to gold.
i might carve out special uses for special licences.
for this i need freedom to change the license.
i can not just change the freedoms granted under private use. 

i might add something to the license like
educational use is exempt but voluntary licensing will be considered as sponsorship and published as such.
i might also publish a list of contributions and list of sponsors with each coherence lifecycle.

vendor installs are not considered commercial use. they fall under for-self. 
the intent of the license is among other to drown the open source ecosystem in money as a function of its adoption (delta') and usage (absolute).

* todo
** institutional use implements a definition of an application of "computational use" which has a substructure for training use.
when using this system to train an llm, gpt, diffusor or or or.
cost per flop.
no, makes no sense. must be something internal. hmm


** flat license of 1 current per month per person (10c/year)
** public benefit 
private market revenue is quartered into { infrastructure dependencies contributors vivalence }
infrastructure = f(storage compute ops{devops} gas{fees,current,tokens})

** the typology has to be explicitly protected against copy with commercial intent for code outside this systems scope.

** explicitly retain all rights 
** add mechanism for revoking and updating the past licence versions retroactively
** advertisement
this product is not allowed to be used for one-to-many signaling sponsored by a third party in any shape way or form.


** ip theft
maybe one way to ensure that intellectual property theft is kept to a minimum, or at least force certain values, is
to mandate that any derivative work that implements any IP, design, whatever, et al has to be published under a licence implementing the same constraints.
