viva: your ~home~ on any device.

think of it as a mix of cloud9, emacs and something wholy new.

the truely new thing about viva is that its a modular agentic functional symbolic operating system.
currently sufficiently equiped to teach you any language. but can be trivially expanded to almost anything afaict.
probably any task that our tiny monkey brains can specify with sufficient accuracy.
its a thin functional wrapper around language. this system is insane.

bring your own symbols (ontology) and entities (domain). bring your own business logic, views and services incl. database & auth (modules).

the system is based on a few powerful primitives and is (if you permit the self-flattery) brilliantly abstracted.


das internet dem individuum.
cybernetically enhanced education system, designed to outlive all of us.

ai has changed how we build systems.

viva was build around the idea that people shouldnt go to applications, applications should come to the people.

problems are soluable.
problems are inevitable.

Less is More, Code is Data, Schema is God. Good is what works in Context.

the planetscale education system.
practice everything like you mean to.


fair source.
categorically free for private use, forever. self hosting and hacking are part of the idea. go nuts.
learn how to aquire a flat, predictable commercial use license.
(licence cost rises logarithmically with with # of active users and rounds to 0 for anything below 1000 active users/year).
(software is provided as is. there is no security implemented and this system is entirely open as of now. this is due to resource constraints and remedies are known to be required.)
prices of licences are roughly oriennted at the price of gold as the true north of value. (delimiter / gauge)






vivalence is
- designed to become the worlds education systems backbone. 
- a datadriven, ai-enabled, private application system, with a registry, a marketplace and shared abstractions.
- infinitely personalizable, hackable, emacs inspired, cybernetically enhanced, federateable, procedurally generated, fair use, functional platform.
- treats privacy and ownership as a saferoom against the tyranny of our mis-incentivized internet.
- fair source, for profit, privately held, eu inc.


enough yapping.
```
kill $(ps -eo pid,pgid | jq -sr '.[] | select(.group == "yapper") | .pid' <(awk '{print "{\"pid\": "$1", \"group\": "$2"}"}'))
```




* comparisons
how does it compare to Anki?
how does it compare to LLMs?

* inspirations
emacs for hackability and longevity
spacex for scale and ambition
public education for the motivation


* identity
** why
make learning anything as easy as trinity learning to fly a b-21 helicopter.
what if you had a system available,
that you tell what skill you want to be able to perform, or what thing you want to accomplish,
and it maps your path from is to ought and teaches you every step until youve mastered it.
i can do that for any skill thats measurable.

** vision
the entirety of humanities competence,
encoded and optimized and transmitted,
between any persons and available to anyone.

tradeoffs and all.
** mission
be the global competence transfer layer for humanity.
like the internet is for information or facebook is for social.

* values
we practice service.
we are curious.
    driven
    epistemologically humble
we are patient.
    deliberate.
    the system never goes out of coherence.
    every work on the system is work on the whole system.
we are dangerous.
    persistant.
    mercyless.
    effective efficient sustained

** curiosity
*** optimise for learning
doing is linear, learning is log.
errors in estimates of doing are exponentially smaller than in discovery
so is the value of output. maybe value of learning is cubic.

*** humility
you dont know shit.

** dedication
*** disciplin
*** focus
** service
*** provide value 
*** solve the problem




enough yapping.
kill $(ps -eo pid,pgid | jq -sr '.[] | select(.group == "yapper") | .pid' <(awk '{print "{\"pid\": "$1", \"group\": "$2"}"}'))




escape velocity. 
When the Foundation was founded, Harry Seldon sold it to the emperor as a colony to backup humanities skills and knowledge. That colony must have used some software system to encode all those skills for transit (not of space and time, but across generations).
This is that system.


what does in transit mean?
it means the space between our brains. the resting place where information resides before someone picks it up to learn it. and after it was encoded by those who already mastered it.
vivalence is a system to encode and practice skills.

whats a skill?

how does it work? hierarchy of knowledge, measurability, critical path, games.

whats a users primary focus? goals and games. you play games untill a dependency is met. then you play more difficult games.

vivalence is a noun. „with vivalence“.

build the young ladys illustrated primer.
build a individualized, reactive museeum tour.
teach your electricity for kids box to each kid individually.
make the documentation for your software project interactive
test a user's knowledge of each ontity in your documentation individually.


learn to play interstellar on an epiano in 10 weeks. 

run your own curriculum while you learn. 

create agents that write lessons like wallace and grommet lay train tracks. 
you learning things (train) - vivalence (track)
classified, procedurally generated. measured. 

create a shared brainspace, populated by symbols and tools.

chart the graph of your learning trajectory for the next schmuk. like woodgrains worn of a long corridors floor between the sciences and the humanities.

education is a qualitative trait we invoke. beeing well educated is axiomatically good.
the philosophical wonder of education is that its both normative and procedural.
it is allways good and more is better.
education differs from the neutral record of information, also named knowledge.
education is the quality thats refered when we aspire to live well.
education is an aspiration. to be rolled up the hill for all of our eternity.
the quality of the steps taken.


rolling release presentation cycle.
only one head, system is expected to be in coherence.

its the last piece of software youll ever have to learn. and a lifetime to master.

