name: nlp-stanza

services:
  stanza-nlp:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - STANZA_LANGUAGES=${STANZA_LANGUAGES}
        - STANZA_PROCESSORS=${STANZA_PROCESSORS}
    container_name: vivalence-service_nlp-stanza
    command: "./entrypoint.sh"
    volumes:
      - ${SERVICE_DATA}/mnt:/app/stanza/mnt
    environment:
      - STANZA_RESOURCES_DIR=/app/stanza/mnt/stanza_resources
      - STANZA_LANGUAGES=${STANZA_LANGUAGES}
      - STANZA_PROCESSORS=${STANZA_PROCESSORS}
      - GUNICORN_WORKERS=${GUNICORN_WORKERS}
      - SERVICE_PORT=${SERVICE_PORT}
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVICE_PORT}/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
