// const createNumberedType = (prefix, count = 4) => {return Array.from({ length: count }, (_, i) => i + 1).reduce((nums, num) => ({...nums, [num]: `var(--colors-${prefix}-${prefix})`,}), {},);};

const createSemanticVariant = (prefix) => ({
  surface: `var(--colors-${prefix}-surface)`,
  contrast: `var(--colors-${prefix}-contrast)`,
  boundary: `var(--colors-${prefix}-boundary)`,
  "hover-surface": `var(--colors-${prefix}-hover-surface)`,
  "hover-contrast": `var(--colors-${prefix}-hover-contrast)`,
  "hover-boundary": `var(--colors-${prefix}-hover-boundary)`,
});

export default {
  colors: {
    palette: {
      white: "var(--colors-palette-white)",
      black: "var(--colors-palette-black)",
      gray: {
        //suck a dick.
        0: "var(--colors-palette-gray-0)",
        10: "var(--colors-palette-gray-10)",
        20: "var(--colors-palette-gray-20)",
        30: "var(--colors-palette-gray-30)",
        40: "var(--colors-palette-gray-40)",
        50: "var(--colors-palette-gray-50)",
        60: "var(--colors-palette-gray-60)",
        70: "var(--colors-palette-gray-70)",
        80: "var(--colors-palette-gray-80)",
        90: "var(--colors-palette-gray-90)",
        100: "var(--colors-palette-gray-100)",
        200: "var(--colors-palette-gray-200)",
        300: "var(--colors-palette-gray-300)",
        400: "var(--colors-palette-gray-400)",
        500: "var(--colors-palette-gray-500)",
        600: "var(--colors-palette-gray-600)",
        700: "var(--colors-palette-gray-700)",
        800: "var(--colors-palette-gray-800)",
        900: "var(--colors-palette-gray-900)",
        1000: "var(--colors-palette-gray-1000)",
      },
    },
    "skeleton-app-link": "var(--colors-skeleton-app-link)",
    "skeleton-app-surface": "var(--colors-skeleton-app-surface)",

    "skeleton-1": createSemanticVariant("skeleton-1"),
    "skeleton-2": createSemanticVariant("skeleton-2"),
    "skeleton-3": createSemanticVariant("skeleton-3"),
    "skeleton-4": createSemanticVariant("skeleton-4"),

    "system-info": createSemanticVariant("system-info"),
    "system-success": createSemanticVariant("system-success"),
    "system-warning": createSemanticVariant("system-warning"),
    "system-error": createSemanticVariant("system-error"),
    "system-danger": createSemanticVariant("system-danger"),
    "system-disabled": createSemanticVariant("system-disabled"),

    "theme-primary": createSemanticVariant("theme-primary"),
    "theme-secondary": createSemanticVariant("theme-secondary"),
    "theme-accent": createSemanticVariant("theme-accent"),
  },

  // For now only family and size, needs to be expanded
  fontFamily: {
    brand: "var(--font-family-brand)",
    "serif-heading": "var(--font-family-serif-heading)",
    "serif-text": "var(--font-family-serif-text)",
    "sans-heading": "var(--font-family-sans-heading)",
    "sans-text": "var(--font-family-sans-text)",
    code: "var(--font-family-code)",
  },
  fontSize: {
    xs: ["var(--font-size-xs)", "var(--line-height-xs)"],
    sm: ["var(--font-size-sm)", "var(--line-height-sm)"],
    base: ["var(--font-size-base)", "var(--line-height-base)"],
    md: ["var(--font-size-base)", "var(--line-height-base)"],
    lg: ["var(--font-size-lg)", "var(--line-height-lg)"],
    xl: ["var(--font-size-xl)", "var(--line-height-xl)"],
    "2xl": ["var(--font-size-2xl)", "var(--line-height-2xl)"],
    "3xl": ["var(--font-size-3xl)", "var(--line-height-3xl)"],
    "4xl": ["var(--font-size-4xl)", "var(--line-height-4xl)"],
    "5xl": ["var(--font-size-5xl)", "var(--line-height-5xl)"],
    "6xl": ["var(--font-size-6xl)", "var(--line-height-6xl)"],
    "7xl": ["var(--font-size-7xl)", "var(--line-height-7xl)"],
    "8xl": ["var(--font-size-8xl)", "var(--line-height-8xl)"],
  },
  // tokens
  boxShadow: {
    sm: "var(--box-shadow-sm)",
    DEFAULT: "var(--box-shadow-default)",
    md: "var(--box-shadow-md)",
    lg: "var(--box-shadow-lg)",
    xl: "var(--box-shadow-xl)",
  },
  dropShadow: {
    sm: "var(--drop-shadow-sm)",
    DEFAULT: "var(--drop-shadow-default)",
    md: "var(--drop-shadow-md)",
    lg: "var(--drop-shadow-lg)",
    xl: "var(--drop-shadow-xl)",
    none: "var(--drop-shadow-none)",
  },
  borderRadius: {
    none: "var(--border-radius-none)",
    sm: "var(--border-radius-sm)",
    DEFAULT: "var(--border-radius-default)",
    lg: "var(--border-radius-lg)",
    full: "var(--border-radius-full)",
  },
  extend: {
    spacing: {
      0: "var(--spacing-0)",
      1: "var(--spacing-1)",
      2: "var(--spacing-2)",
      3: "var(--spacing-3)",
      4: "var(--spacing-4)",
      6: "var(--spacing-6)",
      8: "var(--spacing-8)",
    },
    animation: {
      "spin-slow": "var(--animation-spin-slow)",
    },
    container: {
      center: false,
      padding: {
        DEFAULT: "var(--container-padding-default)",
        sm: "var(--container-padding-sm)",
        lg: "var(--container-padding-lg)",
      },
    },
    screens: {
      xs: "320px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    typography: {
      DEFAULT: {
        css: {
          "--tw-prose-body": "var(--colors-skeleton-1-contrast)",
          "--tw-prose-bold": "var(--colors-skeleton-2-contrast)",
          "--tw-prose-headings": "var(--colors-skeleton-2-contrast)",
          "--tw-prose-bullets": "var(--colors-skeleton-2-contrast)",
          "--tw-prose-lead": "var(--colors-skeleton-1-contrast)",
          "--tw-prose-links": "var(--colors-skeleton-app-link)",
          "--tw-prose-captions": "var(--colors-skeleton-1-contrast)",
          "--tw-prose-code": "var(--colors-skeleton-1-contrast)",
          "--tw-prose-pre-code": "var(--colors-skeleton-1-contrast)",
          "--tw-prose-quotes": "var(--colors-skeleton-1-contrast)",
          "--tw-prose-counters": "var(--colors-skeleton-1-contrast)",
          "--tw-prose-hr": "var(--colors-skeleton-1-boundary)",
          "--tw-prose-quote-borders": "var(--colors-skeleton-1-boundary)",
          "--tw-prose-pre-bg": "var(--colors-skeleton-1-surface)",
          "--tw-prose-th-borders": "var(--colors-skeleton-1-boundary)",
          "--tw-prose-td-borders": "var(--colors-skeleton-1-boundary)",
          "--tw-prose-invert-body": "var(--colors-skeleton-2-contrast)",
          "--tw-prose-invert-headings": "var(--colors-palette-white)",
          "--tw-prose-invert-lead": "var(--colors-skeleton-1-contrast)",
          "--tw-prose-invert-links": "var(--colors-theme-primary-solid)",
          "--tw-prose-invert-bold": "var(--colors-palette-white)",
          "--tw-prose-invert-counters": "var(--colors-skeleton-1-contrast)",
          "--tw-prose-invert-bullets": "var(--colors-skeleton-1-contrast)",
          "--tw-prose-invert-hr": "var(--colors-skeleton-3-boundary)",
          "--tw-prose-invert-quotes": "var(--colors-skeleton-1-contrast)",
          "--tw-prose-invert-quote-borders":
            "var(--colors-skeleton-3-boundary)",
          "--tw-prose-invert-captions": "var(--colors-skeleton-1-contrast)",
          "--tw-prose-invert-code": "var(--colors-theme-primary-solid)",
          "--tw-prose-invert-pre-code": "var(--colors-skeleton-1-contrast)",
          "--tw-prose-invert-pre-bg": "var(--colors-skeleton-3-surface)",
          "--tw-prose-invert-th-borders": "var(--colors-skeleton-3-boundary)",
          "--tw-prose-invert-td-borders": "var(--colors-skeleton-2-boundary)",
        },
      },
    },
  },
};

// "--tw-prose-body": "var(--colors-skeleton-1-contrast)",
// "--tw-prose-bold": "var(--colors-skeleton-2-contrast)",
// "--tw-prose-headings": "var(--colors-skeleton-2-contrast)",
// "--tw-prose-bullets": "var(--colors-skeleton-2-contrast)",
// "--tw-prose-lead": "var(--colors-skeleton-1-contrast)",
// "--tw-prose-links": "var(--colors-skeleton-app-link)",
// "--tw-prose-captions": "var(--colors-skeleton-contrast-1)",
// "--tw-prose-code": "var(--colors-skeleton-contrast-1)",
// "--tw-prose-pre-code": "var(--colors-skeleton-contrast-1)",
// "--tw-prose-quotes": "var(--colors-skeleton-contrast-1)",
// "--tw-prose-counters": "var(--colors-skeleton-contrast-1)",
// "--tw-prose-hr": "var(--colors-skeleton-boundary-1)",
// "--tw-prose-quote-borders": "var(--colors-skeleton-boundary-1)",
// "--tw-prose-pre-bg": "var(--colors-skeleton-surface-1)",
// "--tw-prose-th-borders": "var(--colors-skeleton-boundary-1)",
// "--tw-prose-td-borders": "var(--colors-skeleton-boundary-1)",

// // Inverted/dark mode colors
// "--tw-prose-invert-body": "var(--colors-skeleton-contrast-2)",
// "--tw-prose-invert-headings": "var(--colors-palette-white)",
// "--tw-prose-invert-lead": "var(--colors-skeleton-contrast-1)",
// "--tw-prose-invert-links": "var(--colors-theme-primary-solid)",
// "--tw-prose-invert-bold": "var(--colors-palette-white)",
// "--tw-prose-invert-counters": "var(--colors-skeleton-contrast-1)",
// "--tw-prose-invert-bullets": "var(--colors-skeleton-contrast-1)",
// "--tw-prose-invert-hr": "var(--colors-skeleton-boundary-3)",
// "--tw-prose-invert-quotes": "var(--colors-skeleton-contrast-1)",
// "--tw-prose-invert-quote-borders":
//   "var(--colors-skeleton-boundary-3)",
// "--tw-prose-invert-captions": "var(--colors-skeleton-contrast-1)",
// "--tw-prose-invert-code": "var(--colors-theme-primary-solid)",
// "--tw-prose-invert-pre-code": "var(--colors-skeleton-contrast-1)",
// "--tw-prose-invert-pre-bg": "var(--colors-skeleton-surface-3)",
// "--tw-prose-invert-th-borders": "var(--colors-skeleton-boundary-3)",
// "--tw-prose-invert-td-borders": "var(--colors-skeleton-boundary-2)",
// const createNumberedType = (prefix, count = 4) => {
//   return Array.from({ length: count }, (_, i) => i + 1).reduce(
//     (nums, num) => ({
//       ...nums,
//       // [num]: `var(--colors-${num}-${prefix})`,
//       // [num]: `var(--colors-${prefix}-${num})`,
//       [num]: `var(--colors-${prefix}-${num})`,
//     }),
//     {},
//   );
// };

// const createSemanticVariant = (prefix) => ({
//   surface: `var(--colors-${prefix}-surface)`,
//   contrast: `var(--colors-${prefix}-contrast)`,
//   boundary: `var(--colors-${prefix}-boundary)`,
//   "hover-surface": `var(--colors-${prefix}-hover-surface)`,
//   "hover-contrast": `var(--colors-${prefix}-hover-contrast)`,
//   "hover-boundary": `var(--colors-${prefix}-hover-boundary)`,
// });

// export default {
//   colors: {
//     palette: {
//       white: "var(--colors-palette-white)",
//       black: "var(--colors-palette-black)",
//       gray: {
//         // suck it
//         0: "var(--colors-palette-gray-0)",
//         10: "var(--colors-palette-gray-10)",
//         20: "var(--colors-palette-gray-20)",
//         30: "var(--colors-palette-gray-30)",
//         40: "var(--colors-palette-gray-40)",
//         50: "var(--colors-palette-gray-50)",
//         60: "var(--colors-palette-gray-60)",
//         70: "var(--colors-palette-gray-70)",
//         80: "var(--colors-palette-gray-80)",
//         90: "var(--colors-palette-gray-90)",
//         100: "var(--colors-palette-gray-100)",
//         200: "var(--colors-palette-gray-200)",
//         300: "var(--colors-palette-gray-300)",
//         400: "var(--colors-palette-gray-400)",
//         500: "var(--colors-palette-gray-500)",
//         600: "var(--colors-palette-gray-600)",
//         700: "var(--colors-palette-gray-700)",
//         800: "var(--colors-palette-gray-800)",
//         900: "var(--colors-palette-gray-900)",
//         1000: "var(--colors-palette-gray-1000)",
//       },
//     },
//     "skeleton-app-link": "var(--colors-skeleton-app-link)",
//     "skeleton-app-surface": "var(--colors-skeleton-app-surface)",
//     "skeleton-surface": createNumberedType("skeleton-surface", 4),
//     "skeleton-contrast": createNumberedType("skeleton-contrast", 4),
//     "skeleton-boundary": createNumberedType("skeleton-boundary", 4),

//     "system-info": createSemanticVariant("system-info"),
//     "system-success": createSemanticVariant("system-success"),
//     "system-warning": createSemanticVariant("system-warning"),
//     "system-error": createSemanticVariant("system-error"),
//     "system-danger": createSemanticVariant("system-danger"),
//     "system-disabled": createSemanticVariant("system-disabled"),

//     "theme-primary": createSemanticVariant("theme-primary"),
//     "theme-secondary": createSemanticVariant("theme-secondary"),
//     "theme-accent": createSemanticVariant("theme-accent"),
//   },

//   // For now only family and size, needs to be expanded
//   fontFamily: {
//     brand: "var(--font-family-brand)",
//     "serif-head": "var(--font-family-serif-head)",
//     "serif-text": "var(--font-family-serif-text)",
//     "sans-head": "var(--font-family-sans-head)",
//     "sans-text": "var(--font-family-sans-text)",
//     code: "var(--font-family-code)",
//   },
//   fontSize: {
//     xs: ["var(--font-size-xs)", "var(--line-height-xs)"],
//     sm: ["var(--font-size-sm)", "var(--line-height-sm)"],
//     base: ["var(--font-size-base)", "var(--line-height-base)"],
//     md: ["var(--font-size-base)", "var(--line-height-base)"],
//     lg: ["var(--font-size-lg)", "var(--line-height-lg)"],
//     xl: ["var(--font-size-xl)", "var(--line-height-xl)"],
//     "2xl": ["var(--font-size-2xl)", "var(--line-height-2xl)"],
//     "3xl": ["var(--font-size-3xl)", "var(--line-height-3xl)"],
//     "4xl": ["var(--font-size-4xl)", "var(--line-height-4xl)"],
//     "5xl": ["var(--font-size-5xl)", "var(--line-height-5xl)"],
//     "6xl": ["var(--font-size-6xl)", "var(--line-height-6xl)"],
//     "7xl": ["var(--font-size-7xl)", "var(--line-height-7xl)"],
//     "8xl": ["var(--font-size-8xl)", "var(--line-height-8xl)"],
//   },
//   // tokens
//   boxShadow: {
//     sm: "var(--box-shadow-sm)",
//     DEFAULT: "var(--box-shadow-default)",
//     md: "var(--box-shadow-md)",
//     lg: "var(--box-shadow-lg)",
//     xl: "var(--box-shadow-xl)",
//   },
//   dropShadow: {
//     sm: "var(--drop-shadow-sm)",
//     DEFAULT: "var(--drop-shadow-default)",
//     md: "var(--drop-shadow-md)",
//     lg: "var(--drop-shadow-lg)",
//     xl: "var(--drop-shadow-xl)",
//     none: "var(--drop-shadow-none)",
//   },
//   borderRadius: {
//     none: "var(--border-radius-none)",
//     sm: "var(--border-radius-sm)",
//     DEFAULT: "var(--border-radius-default)",
//     lg: "var(--border-radius-lg)",
//     full: "var(--border-radius-full)",
//   },
//   extend: {
//     spacing: {
//       0: "var(--spacing-0)",
//       1: "var(--spacing-1)",
//       2: "var(--spacing-2)",
//       3: "var(--spacing-3)",
//       4: "var(--spacing-4)",
//       6: "var(--spacing-6)",
//       8: "var(--spacing-8)",
//     },
//     animation: {
//       "spin-slow": "var(--animation-spin-slow)",
//     },
//     container: {
//       center: false,
//       padding: {
//         DEFAULT: "var(--container-padding-default)",
//         sm: "var(--container-padding-sm)",
//         lg: "var(--container-padding-lg)",
//       },
//     },
//     screens: {
//       xs: "320px",
//       sm: "640px",
//       md: "768px",
//       lg: "1024px",
//       xl: "1280px",
//       "2xl": "1536px",
//     },
//     typography: {
//       DEFAULT: {
//         css: {
//           "--tw-prose-body": "var(--colors-skeleton-contrast-1)",
//           "--tw-prose-bold": "var(--colors-skeleton-contrast-2)",
//           "--tw-prose-headings": "var(--colors-skeleton-contrast-2)",
//           "--tw-prose-bullets": "var(--colors-skeleton-contrast-2)",
//           "--tw-prose-lead": "var(--colors-skeleton-contrast-1)",
//           "--tw-prose-links": "var(--colors-skeleton-app-link)",
//           "--tw-prose-captions": "var(--colors-skeleton-contrast-1)",
//           "--tw-prose-code": "var(--colors-skeleton-contrast-1)",
//           "--tw-prose-pre-code": "var(--colors-skeleton-contrast-1)",
//           "--tw-prose-quotes": "var(--colors-skeleton-contrast-1)",
//           "--tw-prose-counters": "var(--colors-skeleton-contrast-1)",
//           "--tw-prose-hr": "var(--colors-skeleton-boundary-1)",
//           "--tw-prose-quote-borders": "var(--colors-skeleton-boundary-1)",
//           "--tw-prose-pre-bg": "var(--colors-skeleton-surface-1)",
//           "--tw-prose-th-borders": "var(--colors-skeleton-boundary-1)",
//           "--tw-prose-td-borders": "var(--colors-skeleton-boundary-1)",

//           // Inverted/dark mode colors
//           "--tw-prose-invert-body": "var(--colors-skeleton-contrast-2)",
//           "--tw-prose-invert-headings": "var(--colors-palette-white)",
//           "--tw-prose-invert-lead": "var(--colors-skeleton-contrast-1)",
//           "--tw-prose-invert-links": "var(--colors-theme-primary-solid)",
//           "--tw-prose-invert-bold": "var(--colors-palette-white)",
//           "--tw-prose-invert-counters": "var(--colors-skeleton-contrast-1)",
//           "--tw-prose-invert-bullets": "var(--colors-skeleton-contrast-1)",
//           "--tw-prose-invert-hr": "var(--colors-skeleton-boundary-3)",
//           "--tw-prose-invert-quotes": "var(--colors-skeleton-contrast-1)",
//           "--tw-prose-invert-quote-borders":
//             "var(--colors-skeleton-boundary-3)",
//           "--tw-prose-invert-captions": "var(--colors-skeleton-contrast-1)",
//           "--tw-prose-invert-code": "var(--colors-theme-primary-solid)",
//           "--tw-prose-invert-pre-code": "var(--colors-skeleton-contrast-1)",
//           "--tw-prose-invert-pre-bg": "var(--colors-skeleton-surface-3)",
//           "--tw-prose-invert-th-borders": "var(--colors-skeleton-boundary-3)",
//           "--tw-prose-invert-td-borders": "var(--colors-skeleton-boundary-2)",
//         },
//       },
//     },
//   },
// };

// // console.log(JSON.stringify(tailwind));
// // export default tailwind;
