CREATE ROLE postgres WITH LOGIN SUPERUSER CREATEDB CREATEROLE REPLICATION BYPASSRLS PASSWORD ${POSTGRES_PASSWORD};
CREATE ROLE ${POSTGRES_USER} WITH LOGIN SUPERUSER CREATEDB CREATEROLE REPLICATION BYPASSRLS PASSWORD ${POSTGRES_PASSWORD};
