-- AlterTable
ALTER TABLE "Tag" ALTER COLUMN "runtimeId" DROP DEFAULT,
ALTER COLUMN "slug" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Unit" ALTER COLUMN "runtimeId" DROP DEFAULT,
ALTER COLUMN "slug" DROP DEFAULT;
