name: Deploy on Tag

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch

    # tags:
    #   - 'v*.*.*'  # Semantic versioning tags

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print secret (Not Recommended)
      run: echo "secrets.SSH_USER ${{ secrets.SSH_USER }}"
      run: echo "secrets.SSH_HOST ${{ secrets.SSH_HOST }}"
      run: echo "secrets.SSH_KEY ${{ secrets.SSH_KEY }}"

    - name: Build and push Docker images
      run: |
        docker build -t v-test -f Dockerfile.test .
        docker save v-test | ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker load"
        # docker build -t v-frontend ./frontend
        # docker build -t v-backend ./backend
        # docker save v-frontend v-backend | ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker load"

    # - name: Deploy to server
    #   run: |
    #     ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker-compose -f /opt/server/docker-compose.yml up -d"
