name: Deploy on Tag

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch

    # tags:
    #   - 'v*.*.*'  # Semantic versioning tags

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker images
      run: |
        docker build -t v-frontend ./frontend
        docker build -t v-backend ./backend
        docker save v-frontend v-backend | ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker load"

    - name: Deploy to server
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker-compose -f /opt/server/docker-compose.yml up -d"
